// Generated by CoffeeScript 1.10.0
(function() {
  var arr, b, config, message;

  message = require('../utils/message');

  config = require('../../config/default');

  arr = new Uint8Array(26);

  b = 0;

  b += message.writeInt8(b, arr, 0);

  b += message.writeInt8(b, arr, 0);

  b += message.writeInt8(b, arr, 'a'.charCodeAt(0));

  b += message.writeInt24(b, arr, config['game-radius']);

  b += message.writeInt16(b, arr, 411);

  b += message.writeInt16(b, arr, config['sector-size']);

  b += message.writeInt16(b, arr, 144);

  b += message.writeInt8(b, arr, 4.8 * 10);

  b += message.writeInt16(b, arr, 5.39 * 100);

  b += message.writeInt16(b, arr, 0.4 * 100);

  b += message.writeInt16(b, arr, 14 * 100);

  b += message.writeInt16(b, arr, 0.033 * 1e3);

  b += message.writeInt16(b, arr, 0.028 * 1e3);

  b += message.writeInt16(b, arr, 0.43 * 1e3);

  b += message.writeInt8(b, arr, 8);

  module.exports = arr;

}).call(this);
