// Generated by CoffeeScript 1.10.0
(function() {
  var arr, message;

  message = require('../utils/message');

  arr = new Uint8Array(3);

  message.writeInt8(2, arr, 'p'.charCodeAt(0));

  module.exports = arr;

}).call(this);
