// Generated by CoffeeScript 1.10.0
(function() {
  var message, type;

  message = require('../utils/message');

  type = 'W'.charCodeAt(0);

  exports.build = function(x, y) {
    var arr, b;
    arr = new Uint8Array(8);
    b = 0;
    b += message.writeInt8(b, arr, 0);
    b += message.writeInt8(b, arr, 0);
    b += message.writeInt8(b, arr, type);
    b += message.writeInt8(b, arr, x);
    b += message.writeInt8(b, arr, y);
    return arr;
  };

}).call(this);
