// Generated by CoffeeScript 1.10.0
(function() {
  var Food;

  module.exports = Food = (function() {

    /*
    Section: Construction
     */
    function Food(id, position, size, color) {
      this.id = id;
      this.position = position;
      this.size = size;
      this.color = color;
    }

    return Food;

  })();

}).call(this);
