// Generated by CoffeeScript 1.10.0
(function() {
  var Sector;

  module.exports = Sector = (function() {

    /*
    Section: Construction
     */
    function Sector(position, foods) {
      this.position = position;
      this.foods = foods;
    }

    return Sector;

  })();

}).call(this);
